language: generic

dist: trusty

matrix:
    include:
    - env: CXX=g++-8 CC=gcc-8
      addons:
        apt:
          packages:
            - g++-8
            - valgrind
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-7
            - llvm-toolchain-trusty-6.0
            - llvm-toolchain-trusty-5.0
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty-3.9
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
            - valgrind
          sources: *sources
    - env: CXX=g++-6 CC=gcc-6 EXTRA_CMAKE=-DDEFLATE_SUPPORT=Off
      addons:
        apt:
          packages:
            - g++-6
            - valgrind
          sources: *sources
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - valgrind
          sources: *sources
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - valgrind
          sources: *sources
    - env: CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          packages:
            - g++-4.9
            - valgrind
          sources: *sources
    - env: CXX=clang++-7 CC=clang-7
      addons:
        apt:
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-6.0 CC=clang-6.0
      addons:
        apt:
          packages:
            - clang-6.0
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
            - clang-5.0
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-4.0 CC=clang-4.0
      addons:
        apt:
          packages:
            - clang-4.0
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-3.9 CC=clang-3.9 EXTRA_CMAKE=-DCOVERAGE=Off
      addons:
        apt:
          packages:
            - clang-3.9
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          packages:
            - clang-3.7
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-3.6 CC=clang-3.6
      addons:
        apt:
          packages:
            - clang-3.6
            - libc++-dev
            - valgrind
          sources: *sources

install:
    - if [[ "$CXX" == clang* ]]; then export CXXFLAGS="-stdlib=libc++"; fi
    - JOBS=2

before_script:
    - cmake --version
    - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=On ${EXTRA_CMAKE}
    - cmake --build build -- -j${JOBS}

script:
    - cd build
    - cmake --build . --target unittest
    - ctest -D ExperimentalBuild -j${JOBS}
    - ctest -D ExperimentalMemCheck -j${JOBS}
    - bash <(curl -s https://codecov.io/bash)
