image: base/devel
stages:
  - build

before_script:
  - &ins pacman -Sy cmake git

job_build:
  before_script:
    - *ins
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  stage: build