image: codehz/stonebuilder
stages:
  - build
  - package

job_build:
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake .. || (cat CMakeFiles/CMakeOutput.log && cat CMakeFiles/CMakeError.log && exit 1)
    - make
  artifacts:
    paths:
      - build/stone/stone
    expire_in: 20min
  stage: build

job_package:
  script:
    - mkdir -p output/support && cd output
    - cat ../lib32.txt | xargs -I {} cp /usr/lib32/{} support -r
    - cp /usr/lib32/ld-*.so support
    - cp ../build/stone/stone .
  artifacts:
    paths:
      - output
  dependencies:
    - job_build
  stage: package