image: archlinux/base
stages:
  - build

before_script:
  - &ins pacman -Sy base-devel cmake git lib32-glibc --noconfirm --needed

job_build:
  before_script:
    - *ins
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  stage: build