image: codehz/stonebuilder
stages:
  - build
  - package

variables:
  GIT_SUBMODULE_STRATEGY: recursive

job_build:
  script:
    - mkdir build install
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=../install -DCMAKE_BUILD_TYPE=Release .. || (cat CMakeFiles/CMakeOutput.log && cat CMakeFiles/CMakeError.log && exit 1)
    - make
    - make install
  artifacts:
    paths:
      - install/
    expire_in: 20min
  stage: build

job_package:
  script:
    - mkdir -p output/support && cd output
    - cat ../lib32.txt | xargs -I {} cp -Lrv /usr/lib32/{} support/{}
    - cp -Lv /usr/lib32/ld-*.so support/ld.so
    - cp ../install/bin/* .
    - cp /usr/bin/proot .
    - cp ../loader .
    - strip stone
  artifacts:
    paths:
      - output
  dependencies:
    - job_build
  stage: package