image: archlinux/base
stages:
  - build

before_script:
  - &ins pacman -Sy base-devel cmake make git lib32-glibc glibc boost boost-libs --noconfirm --needed

job_build:
  before_script:
    - *ins
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake .. || (cat CMakeFiles/CMakeOutput.log && cat CMakeFiles/CMakeError.log && exit 1)
    - make
  stage: build