image: codehz/stonebuilder
stages:
  - build

job_build:
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake .. || (cat CMakeFiles/CMakeOutput.log && cat CMakeFiles/CMakeError.log && exit 1)
    - make
  stage: build