version: '3'
services:
  redis:
    image: redis
  server:
    image: codehz/stoneserver
    volumes:
      - ./game:/run/game:ro
      - ./data:/run/data:rw
    environment:
      - APID=tcp:redis:6379
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    depends_on:
      - redis

